-- Primer Primitives theme generator
-- Generates standalone colorscheme files that require no runtime dependencies

local M = {}

local palettes = {
  { id = 'dark', file = 'primer_dark' },
  { id = 'light', file = 'primer_light' },
  { id = 'dark_dimmed', file = 'primer_dark_dimmed' },
  { id = 'dark_high_contrast', file = 'primer_dark_high_contrast' },
}

--- Serialize a value to Lua code
---@param value any The value to serialize
---@param indent number The current indentation level
---@return string
local function serialize(value, indent)
  indent = indent or 0
  local spaces = string.rep('  ', indent)

  if type(value) == 'string' then
    return string.format('%q', value)
  elseif type(value) == 'number' then
    return tostring(value)
  elseif type(value) == 'boolean' then
    return tostring(value)
  elseif type(value) == 'table' then
    local parts = {}
    local is_array = #value > 0

    if is_array then
      for _, v in ipairs(value) do
        table.insert(parts, serialize(v, indent + 1))
      end
      return '{ ' .. table.concat(parts, ', ') .. ' }'
    else
      -- Sort keys for deterministic output
      local sorted_keys = {}
      for k in pairs(value) do
        table.insert(sorted_keys, k)
      end
      table.sort(sorted_keys, function(a, b)
        return tostring(a) < tostring(b)
      end)

      for _, k in ipairs(sorted_keys) do
        local v = value[k]
        local key
        if type(k) == 'string' and k:match('^[%a_][%w_]*$') then
          key = k
        else
          key = '[' .. serialize(k) .. ']'
        end
        table.insert(parts, key .. ' = ' .. serialize(v, indent + 1))
      end
      if #parts == 0 then
        return '{}'
      elseif #parts <= 4 and not next(value, next(value)) then
        return '{ ' .. table.concat(parts, ', ') .. ' }'
      else
        return '{\n' .. spaces .. '  ' .. table.concat(parts, ',\n' .. spaces .. '  ') .. '\n' .. spaces .. '}'
      end
    end
  else
    return 'nil'
  end
end

--- Generate the header comment for a colorscheme file
---@param palette table The palette table
---@return string
local function generate_header(palette)
  local lines = {
    '-- ' .. palette.name:gsub('_', ' '):gsub('^%l', string.upper):gsub(' %l', string.upper) .. ' colorscheme',
    '-- Auto-generated by primer-primitives.nvim',
    '-- Based on Primer Primitives (https://primer.style/primitives)',
    '--',
    '-- This file requires NO external dependencies.',
    '',
  }
  return table.concat(lines, '\n')
end

--- Generate the colorscheme initialization code
---@param palette table The palette table
---@return string
local function generate_init(palette)
  local lines = {
    string.format("vim.opt.background = '%s'", palette.background),
    string.format("vim.g.colors_name = '%s'", palette.name),
    '',
    '-- Clear existing highlights',
    "vim.cmd('highlight clear')",
    '',
  }
  return table.concat(lines, '\n')
end

--- Generate the highlight group definitions
---@param groups table The highlight groups table
---@return string
local function generate_highlights(groups)
  local lines = { '-- Set highlight groups' }

  -- Sort keys for consistent output
  local keys = {}
  for k in pairs(groups) do
    table.insert(keys, k)
  end
  table.sort(keys)

  for _, name in ipairs(keys) do
    local hl = groups[name]
    if hl and next(hl) then
      local serialized = serialize(hl)
      table.insert(lines, string.format("vim.api.nvim_set_hl(0, '%s', %s)", name, serialized))
    end
  end

  return table.concat(lines, '\n')
end

--- Generate terminal color definitions
---@param terminal table The terminal colors table
---@return string
local function generate_terminal(terminal)
  local lines = { '', '-- Terminal colors' }

  for i = 0, 15 do
    local color = terminal[i]
    if color then
      table.insert(lines, string.format("vim.g.terminal_color_%d = '%s'", i, color))
    end
  end

  return table.concat(lines, '\n')
end

--- Generate a complete colorscheme file
---@param palette table The palette table
---@param groups table The highlight groups table
---@param terminal table The terminal colors table
---@return string
function M.generate_colorscheme(palette, groups, terminal)
  local parts = {
    generate_header(palette),
    generate_init(palette),
    generate_highlights(groups),
    generate_terminal(terminal),
    '',
    '-- vi:nowrap',
    '',
  }
  return table.concat(parts, '\n')
end

--- Generate all colorscheme files
---@param output_dir string The output directory for colorscheme files
---@return table results Table of { file = path, success = bool, error = string? }
function M.generate_all(output_dir)
  local highlights = require('primer-primitives.highlights')
  local results = {}

  for _, theme in ipairs(palettes) do
    local palette = require('primer-primitives.palettes.' .. theme.id)
    local groups = highlights.build(palette)
    local terminal = highlights.build_terminal(palette)

    local content = M.generate_colorscheme(palette, groups, terminal)
    local file_path = output_dir .. '/' .. theme.file .. '.lua'

    local file = io.open(file_path, 'w')
    if file then
      file:write(content)
      file:close()
      table.insert(results, { file = file_path, success = true })
    else
      table.insert(results, { file = file_path, success = false, error = 'Failed to open file for writing' })
    end
  end

  return results
end

--- Get available palette names
---@return table
function M.get_palettes()
  return vim.tbl_map(function(p)
    return p.id
  end, palettes)
end

return M
