-- Primer Dark High Contrast colorscheme
-- Auto-generated by primer-primitives.nvim
-- Based on Primer Primitives (https://primer.style/primitives)
--
-- This file requires NO external dependencies.

vim.opt.background = 'dark'
vim.g.colors_name = 'primer_dark_high_contrast'

-- Clear existing highlights
vim.cmd('highlight clear')

-- Set highlight groups
vim.api.nvim_set_hl(0, '@attribute', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, '@attribute.builtin', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, '@boolean', { link = "Boolean" })
vim.api.nvim_set_hl(0, '@character', { link = "Character" })
vim.api.nvim_set_hl(0, '@character.special', { link = "SpecialChar" })
vim.api.nvim_set_hl(0, '@comment', { link = "Comment" })
vim.api.nvim_set_hl(0, '@comment.documentation', { fg = "#9198a1" })
vim.api.nvim_set_hl(0, '@comment.error', {
  bold = true,
  fg = "#ff9492"
})
vim.api.nvim_set_hl(0, '@comment.note', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, '@comment.todo', {
  bold = true,
  fg = "#f0b72f"
})
vim.api.nvim_set_hl(0, '@comment.warning', {
  bold = true,
  fg = "#f0b72f"
})
vim.api.nvim_set_hl(0, '@conditional', { link = "Conditional" })
vim.api.nvim_set_hl(0, '@constant', { link = "Constant" })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@constant.macro', { link = "Macro" })
vim.api.nvim_set_hl(0, '@constructor', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, '@debug', { link = "Debug" })
vim.api.nvim_set_hl(0, '@define', { link = "Define" })
vim.api.nvim_set_hl(0, '@diff.delta', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, '@diff.minus', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, '@diff.plus', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, '@error', { link = "Error" })
vim.api.nvim_set_hl(0, '@exception', { link = "Exception" })
vim.api.nvim_set_hl(0, '@field', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, '@float', { link = "Float" })
vim.api.nvim_set_hl(0, '@function', { link = "Function" })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, '@function.call', { link = "Function" })
vim.api.nvim_set_hl(0, '@function.macro', { link = "Macro" })
vim.api.nvim_set_hl(0, '@function.method', { link = "Function" })
vim.api.nvim_set_hl(0, '@function.method.call', { link = "Function" })
vim.api.nvim_set_hl(0, '@hint', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, '@include', { link = "Include" })
vim.api.nvim_set_hl(0, '@info', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, '@keyword', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@keyword.conditional', { link = "Conditional" })
vim.api.nvim_set_hl(0, '@keyword.conditional.ternary', { link = "Operator" })
vim.api.nvim_set_hl(0, '@keyword.coroutine', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, '@keyword.debug', { link = "Debug" })
vim.api.nvim_set_hl(0, '@keyword.directive', { link = "PreProc" })
vim.api.nvim_set_hl(0, '@keyword.directive.define', { link = "Define" })
vim.api.nvim_set_hl(0, '@keyword.exception', { link = "Exception" })
vim.api.nvim_set_hl(0, '@keyword.function', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@keyword.import', { link = "Include" })
vim.api.nvim_set_hl(0, '@keyword.modifier', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@keyword.operator', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@keyword.repeat', { link = "Repeat" })
vim.api.nvim_set_hl(0, '@keyword.return', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@keyword.type', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@label', { link = "Label" })
vim.api.nvim_set_hl(0, '@lsp.mod.abstract', { italic = true })
vim.api.nvim_set_hl(0, '@lsp.mod.async', { italic = true })
vim.api.nvim_set_hl(0, '@lsp.mod.defaultLibrary', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@lsp.mod.deprecated', { strikethrough = true })
vim.api.nvim_set_hl(0, '@lsp.mod.documentation', { fg = "#9198a1" })
vim.api.nvim_set_hl(0, '@lsp.mod.readonly', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@lsp.mod.static', { italic = true })
vim.api.nvim_set_hl(0, '@lsp.type.class', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, '@lsp.type.comment', { link = "Comment" })
vim.api.nvim_set_hl(0, '@lsp.type.decorator', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, '@lsp.type.enum', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, '@lsp.type.enumMember', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@lsp.type.event', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, '@lsp.type.function', { link = "Function" })
vim.api.nvim_set_hl(0, '@lsp.type.interface', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, '@lsp.type.keyword', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@lsp.type.macro', { link = "Macro" })
vim.api.nvim_set_hl(0, '@lsp.type.method', { link = "Function" })
vim.api.nvim_set_hl(0, '@lsp.type.modifier', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@lsp.type.namespace', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, '@lsp.type.number', { link = "Number" })
vim.api.nvim_set_hl(0, '@lsp.type.operator', { link = "Operator" })
vim.api.nvim_set_hl(0, '@lsp.type.parameter', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, '@lsp.type.property', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, '@lsp.type.regexp', { fg = "#addcff" })
vim.api.nvim_set_hl(0, '@lsp.type.string', { link = "String" })
vim.api.nvim_set_hl(0, '@lsp.type.struct', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, '@lsp.type.type', { link = "Type" })
vim.api.nvim_set_hl(0, '@lsp.type.typeParameter', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, '@lsp.type.variable', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, '@macro', { link = "Macro" })
vim.api.nvim_set_hl(0, '@markup.heading', { link = "Title" })
vim.api.nvim_set_hl(0, '@markup.heading.1', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, '@markup.heading.2', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, '@markup.heading.3', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, '@markup.heading.4', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, '@markup.heading.5', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, '@markup.heading.6', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, '@markup.italic', {
  italic = true,
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, '@markup.link', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, '@markup.link.label', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, '@markup.link.url', {
  underline = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, '@markup.list', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, '@markup.list.checked', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, '@markup.list.unchecked', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, '@markup.math', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@markup.quote', {
  italic = true,
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, '@markup.raw', { fg = "#addcff" })
vim.api.nvim_set_hl(0, '@markup.raw.block', { fg = "#addcff" })
vim.api.nvim_set_hl(0, '@markup.strikethrough', {
  strikethrough = true,
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, '@markup.strong', {
  bold = true,
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, '@markup.underline', { underline = true })
vim.api.nvim_set_hl(0, '@method', { link = "Function" })
vim.api.nvim_set_hl(0, '@method.call', { link = "Function" })
vim.api.nvim_set_hl(0, '@module', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, '@module.builtin', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@namespace', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, '@number', { link = "Number" })
vim.api.nvim_set_hl(0, '@number.float', { link = "Float" })
vim.api.nvim_set_hl(0, '@operator', { link = "Operator" })
vim.api.nvim_set_hl(0, '@parameter', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, '@preproc', { link = "PreProc" })
vim.api.nvim_set_hl(0, '@property', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, '@punctuation', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, '@punctuation.special', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, '@repeat', { link = "Repeat" })
vim.api.nvim_set_hl(0, '@storageclass', { link = "StorageClass" })
vim.api.nvim_set_hl(0, '@string', { link = "String" })
vim.api.nvim_set_hl(0, '@string.documentation', { fg = "#9198a1" })
vim.api.nvim_set_hl(0, '@string.escape', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@string.regex', { fg = "#addcff" })
vim.api.nvim_set_hl(0, '@string.regexp', { fg = "#addcff" })
vim.api.nvim_set_hl(0, '@string.special', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@string.special.path', { fg = "#addcff" })
vim.api.nvim_set_hl(0, '@string.special.symbol', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@string.special.url', {
  underline = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, '@structure', { link = "Structure" })
vim.api.nvim_set_hl(0, '@tag', { link = "Tag" })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, '@tag.builtin', { link = "Tag" })
vim.api.nvim_set_hl(0, '@tag.delimiter', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, '@text', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, '@text.literal', { link = "String" })
vim.api.nvim_set_hl(0, '@text.reference', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, '@text.title', { link = "Title" })
vim.api.nvim_set_hl(0, '@text.todo', { link = "Todo" })
vim.api.nvim_set_hl(0, '@text.underline', { underline = true })
vim.api.nvim_set_hl(0, '@text.uri', {
  underline = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, '@type', { link = "Type" })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@type.definition', { link = "Type" })
vim.api.nvim_set_hl(0, '@type.qualifier', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@variable', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@variable.member', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, '@variable.parameter', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, '@variable.parameter.builtin', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, '@warning', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'Added', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'Boolean', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, 'Changed', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'Character', { fg = "#addcff" })
vim.api.nvim_set_hl(0, 'CmpItemAbbr', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', {
  strikethrough = true,
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'CmpItemKind', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'CmpItemKindClass', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, 'CmpItemKindColor', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, 'CmpItemKindConstructor', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, 'CmpItemKindDefault', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, 'CmpItemKindEvent', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, 'CmpItemKindField', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, 'CmpItemKindFile', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'CmpItemKindFolder', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, 'CmpItemKindModule', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, 'CmpItemKindOperator', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'CmpItemKindProperty', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, 'CmpItemKindReference', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', { fg = "#d3abff" })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, 'CmpItemKindText', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, 'CmpItemKindUnit', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, 'CmpItemKindValue', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, 'CmpItemKindVariable', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, 'CmpItemMenu', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = "#151b23" })
vim.api.nvim_set_hl(0, 'Comment', {
  italic = true,
  fg = "#9198a1"
})
vim.api.nvim_set_hl(0, 'ComplMatchIns', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, 'Conceal', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'Conditional', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'Constant', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, 'CurSearch', { link = "IncSearch" })
vim.api.nvim_set_hl(0, 'Cursor', {
  bg = "#ffffff",
  fg = "#010409"
})
vim.api.nvim_set_hl(0, 'CursorColumn', { link = "CursorLine" })
vim.api.nvim_set_hl(0, 'CursorIM', { link = "Cursor" })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = "#151b23" })
vim.api.nvim_set_hl(0, 'CursorLineFold', {
  bg = "#151b23",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'CursorLineNr', {
  bold = true,
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'CursorLineSign', { bg = "#151b23" })
vim.api.nvim_set_hl(0, 'Debug', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'Define', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'Delimiter', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'DiagnosticDeprecated', {
  sp = "#ff9492",
  strikethrough = true
})
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingError', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingHint', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingInfo', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingOk', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingWarn', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'DiagnosticOk', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'DiagnosticSignError', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'DiagnosticSignHint', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'DiagnosticSignInfo', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'DiagnosticSignOk', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'DiagnosticSignWarn', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', {
  undercurl = true,
  sp = "#ff9492"
})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', {
  undercurl = true,
  sp = "#2bd853"
})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', {
  undercurl = true,
  sp = "#74b9ff"
})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineOk', {
  undercurl = true,
  sp = "#2bd853"
})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', {
  undercurl = true,
  sp = "#f0b72f"
})
vim.api.nvim_set_hl(0, 'DiagnosticUnnecessary', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', {
  bg = "#1b1115",
  fg = "#ff9492"
})
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', {
  bg = "#022111",
  fg = "#2bd853"
})
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', {
  fg = "#74b9ff",
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextOk', {
  bg = "#022111",
  fg = "#2bd853"
})
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', {
  bg = "#241d0d",
  fg = "#f0b72f"
})
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'DiffAdd', { bg = "#022111" })
vim.api.nvim_set_hl(0, 'DiffChange', { bg = "#241d0d" })
vim.api.nvim_set_hl(0, 'DiffDelete', { bg = "#1b1115" })
vim.api.nvim_set_hl(0, 'DiffText', { bg = "#7b4900" })
vim.api.nvim_set_hl(0, 'Directory', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'Error', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'Exception', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'Float', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, 'FloatBorder', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'FloatFooter', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'FloatTitle', {
  fg = "#ffffff",
  bold = true,
  bg = "#010409"
})
vim.api.nvim_set_hl(0, 'FoldColumn', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'Folded', {
  bg = "#151b23",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'Function', { fg = "#dbb7ff" })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'GitSignsAddLn', { bg = "#022111" })
vim.api.nvim_set_hl(0, 'GitSignsAddNr', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'GitSignsChangeLn', { bg = "#241d0d" })
vim.api.nvim_set_hl(0, 'GitSignsChangeNr', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'GitSignsDeleteLn', { bg = "#1b1115" })
vim.api.nvim_set_hl(0, 'GitSignsDeleteNr', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'IblIndent', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'IblScope', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'IblWhitespace', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'Identifier', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'Ignore', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'IncSearch', {
  bg = "#194fb1",
  fg = "#010409"
})
vim.api.nvim_set_hl(0, 'Include', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'IndentBlanklineChar', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextChar', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextStart', {
  underline = true,
  sp = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceChar', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceCharBlankline', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'Keyword', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'Label', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'LazyButton', {
  bg = "#151b23",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'LazyButtonActive', {
  bg = "#194fb1",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'LazyCommit', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'LazyCommitType', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'LazyH1', {
  fg = "#ffffff",
  bold = true,
  bg = "#194fb1"
})
vim.api.nvim_set_hl(0, 'LazyH2', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, 'LazyNormal', { link = "NormalFloat" })
vim.api.nvim_set_hl(0, 'LazyReasonCmd', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'LazyReasonEvent', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'LazyReasonFt', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'LazyReasonKeys', { fg = "#d3abff" })
vim.api.nvim_set_hl(0, 'LazyReasonPlugin', { fg = "#d3abff" })
vim.api.nvim_set_hl(0, 'LazyReasonStart', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'LazySpecial', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'LineNr', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'LineNrAbove', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'LineNrBelow', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'LspCodeLens', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'LspCodeLensSeparator', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'LspInlayHint', {
  bg = "#151b23",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'LspReferenceRead', {
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'LspReferenceTarget', {
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'LspReferenceText', {
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'LspReferenceWrite', {
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'LspSignatureActiveParameter', {
  fg = "#74b9ff",
  underline = true,
  bold = true
})
vim.api.nvim_set_hl(0, 'Macro', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, 'MatchParen', {
  blend = 85,
  bg = "#0a1522",
  bold = true
})
vim.api.nvim_set_hl(0, 'ModeMsg', {
  bold = true,
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'MoreMsg', {
  bold = true,
  fg = "#2bd853"
})
vim.api.nvim_set_hl(0, 'MsgArea', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'MsgSeparator', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'NeoTreeDirectoryIcon', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'NeoTreeDirectoryName', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'NeoTreeEndOfBuffer', { fg = "#010409" })
vim.api.nvim_set_hl(0, 'NeoTreeFileIcon', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'NeoTreeFileName', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'NeoTreeGitAdded', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'NeoTreeGitConflict', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'NeoTreeGitDeleted', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'NeoTreeGitIgnored', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'NeoTreeGitModified', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'NeoTreeGitStaged', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'NeoTreeGitUnstaged', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'NeoTreeGitUntracked', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'NeoTreeIndentMarker', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'NeoTreeNormal', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'NeoTreeNormalNC', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'NeoTreeRootName', {
  bold = true,
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'NonText', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'Normal', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'NormalFloat', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'NormalNC', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'Number', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, 'NvimTreeEmptyFolderName', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'NvimTreeEndOfBuffer', { fg = "#010409" })
vim.api.nvim_set_hl(0, 'NvimTreeFolderIcon', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'NvimTreeFolderName', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'NvimTreeGitDeleted', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'NvimTreeGitDirty', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'NvimTreeGitNew', { fg = "#2bd853" })
vim.api.nvim_set_hl(0, 'NvimTreeImageFile', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'NvimTreeIndentMarker', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'NvimTreeNormal', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'NvimTreeOpenedFolderName', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'NvimTreeRootFolder', {
  bold = true,
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'NvimTreeSpecialFile', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'NvimTreeSymlink', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'Operator', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'Pmenu', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'PmenuExtra', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'PmenuExtraSel', {
  fg = "#b7bdc8",
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'PmenuKind', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'PmenuKindSel', {
  fg = "#b7bdc8",
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'PmenuMatch', {
  fg = "#74b9ff",
  bold = true,
  bg = "#010409"
})
vim.api.nvim_set_hl(0, 'PmenuMatchSel', {
  blend = 85,
  fg = "#74b9ff",
  bold = true,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = "#151b23" })
vim.api.nvim_set_hl(0, 'PmenuSel', {
  fg = "#ffffff",
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'PreCondit', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'PreProc', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'Question', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'QuickFixLine', {
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'Removed', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'Repeat', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'Search', {
  bg = "#7b4900",
  fg = "#010409"
})
vim.api.nvim_set_hl(0, 'SignColumn', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'SnippetTabstop', {
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'Special', { fg = "#91cbff" })
vim.api.nvim_set_hl(0, 'SpecialChar', { fg = "#addcff" })
vim.api.nvim_set_hl(0, 'SpecialComment', {
  italic = true,
  fg = "#9198a1",
  bold = true
})
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'SpellBad', {
  undercurl = true,
  sp = "#ff9492"
})
vim.api.nvim_set_hl(0, 'SpellCap', {
  undercurl = true,
  sp = "#f0b72f"
})
vim.api.nvim_set_hl(0, 'SpellLocal', {
  undercurl = true,
  sp = "#74b9ff"
})
vim.api.nvim_set_hl(0, 'SpellRare', {
  undercurl = true,
  sp = "#d3abff"
})
vim.api.nvim_set_hl(0, 'Statement', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'StatusLine', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'StatusLineNC', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'StatusLineTerm', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'StatusLineTermNC', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'StorageClass', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'String', { fg = "#addcff" })
vim.api.nvim_set_hl(0, 'Structure', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'Substitute', {
  bg = "#ad0116",
  fg = "#010409"
})
vim.api.nvim_set_hl(0, 'TabLine', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = "#010409" })
vim.api.nvim_set_hl(0, 'TabLineSel', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'Tag', { fg = "#72f088" })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { link = "FloatBorder" })
vim.api.nvim_set_hl(0, 'TelescopeMatching', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, 'TelescopeMultiSelection', {
  fg = "#ffffff",
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'TelescopeNormal', { link = "NormalFloat" })
vim.api.nvim_set_hl(0, 'TelescopePreviewBorder', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'TelescopePreviewNormal', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopePromptBorder', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'TelescopePromptNormal', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'TelescopePromptTitle', {
  fg = "#ffffff",
  bold = true,
  bg = "#010409"
})
vim.api.nvim_set_hl(0, 'TelescopeResultsBorder', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'TelescopeResultsNormal', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopeResultsTitle', {
  bg = "#010409",
  fg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopeSelection', { link = "PmenuSel" })
vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'TelescopeTitle', { link = "FloatTitle" })
vim.api.nvim_set_hl(0, 'TermCursor', { link = "Cursor" })
vim.api.nvim_set_hl(0, 'TermCursorNC', {
  bg = "#b7bdc8",
  fg = "#010409"
})
vim.api.nvim_set_hl(0, 'Title', {
  bold = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, 'Todo', {
  bold = true,
  fg = "#f0b72f"
})
vim.api.nvim_set_hl(0, 'Type', { fg = "#ffb757" })
vim.api.nvim_set_hl(0, 'Typedef', { fg = "#ff9492" })
vim.api.nvim_set_hl(0, 'Underlined', {
  underline = true,
  fg = "#74b9ff"
})
vim.api.nvim_set_hl(0, 'VertSplit', { link = "WinSeparator" })
vim.api.nvim_set_hl(0, 'Visual', {
  blend = 85,
  bg = "#0a1522"
})
vim.api.nvim_set_hl(0, 'VisualNOS', { link = "Visual" })
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = "#f0b72f" })
vim.api.nvim_set_hl(0, 'WhichKey', { fg = "#74b9ff" })
vim.api.nvim_set_hl(0, 'WhichKeyBorder', { link = "FloatBorder" })
vim.api.nvim_set_hl(0, 'WhichKeyDesc', { fg = "#ffffff" })
vim.api.nvim_set_hl(0, 'WhichKeyFloat', { link = "NormalFloat" })
vim.api.nvim_set_hl(0, 'WhichKeyGroup', { fg = "#d3abff" })
vim.api.nvim_set_hl(0, 'WhichKeySeparator', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'WhichKeyValue', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'Whitespace', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'WildMenu', { link = "PmenuSel" })
vim.api.nvim_set_hl(0, 'WinBar', {
  fg = "#ffffff",
  bold = true,
  bg = "#010409"
})
vim.api.nvim_set_hl(0, 'WinBarNC', {
  bg = "#010409",
  fg = "#b7bdc8"
})
vim.api.nvim_set_hl(0, 'WinSeparator', { fg = "#b7bdc8" })
vim.api.nvim_set_hl(0, 'lCursor', { link = "Cursor" })

-- Terminal colors
vim.g.terminal_color_0 = '#2f3742'
vim.g.terminal_color_1 = '#ff9492'
vim.g.terminal_color_2 = '#28d751'
vim.g.terminal_color_3 = '#f0b72f'
vim.g.terminal_color_4 = '#71b7ff'
vim.g.terminal_color_5 = '#cb9eff'
vim.g.terminal_color_6 = '#39c5cf'
vim.g.terminal_color_7 = '#f0f6fc'
vim.g.terminal_color_8 = '#656c76'
vim.g.terminal_color_9 = '#ffb1af'
vim.g.terminal_color_10 = '#4ae168'
vim.g.terminal_color_11 = '#f7c843'
vim.g.terminal_color_12 = '#91cbff'
vim.g.terminal_color_13 = '#dbb7ff'
vim.g.terminal_color_14 = '#56d4dd'
vim.g.terminal_color_15 = '#ffffff'

-- vi:nowrap
