-- Primer Light colorscheme
-- Auto-generated by primer-primitives.nvim
-- Based on Primer Primitives (https://primer.style/primitives)
--
-- This file requires NO external dependencies.

vim.opt.background = 'light'
vim.g.colors_name = 'primer_light'

-- Clear existing highlights
vim.cmd('highlight clear')

-- Set highlight groups
vim.api.nvim_set_hl(0, '@attribute', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, '@attribute.builtin', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, '@boolean', { link = "Boolean" })
vim.api.nvim_set_hl(0, '@character', { link = "Character" })
vim.api.nvim_set_hl(0, '@character.special', { link = "SpecialChar" })
vim.api.nvim_set_hl(0, '@comment', { link = "Comment" })
vim.api.nvim_set_hl(0, '@comment.documentation', { fg = "#59636e" })
vim.api.nvim_set_hl(0, '@comment.error', {
  fg = "#d1242f",
  bold = true
})
vim.api.nvim_set_hl(0, '@comment.note', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, '@comment.todo', {
  fg = "#9a6700",
  bold = true
})
vim.api.nvim_set_hl(0, '@comment.warning', {
  fg = "#9a6700",
  bold = true
})
vim.api.nvim_set_hl(0, '@conditional', { link = "Conditional" })
vim.api.nvim_set_hl(0, '@constant', { link = "Constant" })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@constant.macro', { link = "Macro" })
vim.api.nvim_set_hl(0, '@constructor', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, '@debug', { link = "Debug" })
vim.api.nvim_set_hl(0, '@define', { link = "Define" })
vim.api.nvim_set_hl(0, '@diff.delta', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, '@diff.minus', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, '@diff.plus', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, '@error', { link = "Error" })
vim.api.nvim_set_hl(0, '@exception', { link = "Exception" })
vim.api.nvim_set_hl(0, '@field', { fg = "#953800" })
vim.api.nvim_set_hl(0, '@float', { link = "Float" })
vim.api.nvim_set_hl(0, '@function', { link = "Function" })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, '@function.call', { link = "Function" })
vim.api.nvim_set_hl(0, '@function.macro', { link = "Macro" })
vim.api.nvim_set_hl(0, '@function.method', { link = "Function" })
vim.api.nvim_set_hl(0, '@function.method.call', { link = "Function" })
vim.api.nvim_set_hl(0, '@hint', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, '@include', { link = "Include" })
vim.api.nvim_set_hl(0, '@info', { fg = "#0969da" })
vim.api.nvim_set_hl(0, '@keyword', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@keyword.conditional', { link = "Conditional" })
vim.api.nvim_set_hl(0, '@keyword.conditional.ternary', { link = "Operator" })
vim.api.nvim_set_hl(0, '@keyword.coroutine', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, '@keyword.debug', { link = "Debug" })
vim.api.nvim_set_hl(0, '@keyword.directive', { link = "PreProc" })
vim.api.nvim_set_hl(0, '@keyword.directive.define', { link = "Define" })
vim.api.nvim_set_hl(0, '@keyword.exception', { link = "Exception" })
vim.api.nvim_set_hl(0, '@keyword.function', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@keyword.import', { link = "Include" })
vim.api.nvim_set_hl(0, '@keyword.modifier', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@keyword.operator', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@keyword.repeat', { link = "Repeat" })
vim.api.nvim_set_hl(0, '@keyword.return', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@keyword.type', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@label', { link = "Label" })
vim.api.nvim_set_hl(0, '@lsp.mod.abstract', { italic = true })
vim.api.nvim_set_hl(0, '@lsp.mod.async', { italic = true })
vim.api.nvim_set_hl(0, '@lsp.mod.defaultLibrary', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@lsp.mod.deprecated', { strikethrough = true })
vim.api.nvim_set_hl(0, '@lsp.mod.documentation', { fg = "#59636e" })
vim.api.nvim_set_hl(0, '@lsp.mod.readonly', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@lsp.mod.static', { italic = true })
vim.api.nvim_set_hl(0, '@lsp.type.class', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, '@lsp.type.comment', { link = "Comment" })
vim.api.nvim_set_hl(0, '@lsp.type.decorator', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, '@lsp.type.enum', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, '@lsp.type.enumMember', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@lsp.type.event', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, '@lsp.type.function', { link = "Function" })
vim.api.nvim_set_hl(0, '@lsp.type.interface', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, '@lsp.type.keyword', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@lsp.type.macro', { link = "Macro" })
vim.api.nvim_set_hl(0, '@lsp.type.method', { link = "Function" })
vim.api.nvim_set_hl(0, '@lsp.type.modifier', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@lsp.type.namespace', { fg = "#953800" })
vim.api.nvim_set_hl(0, '@lsp.type.number', { link = "Number" })
vim.api.nvim_set_hl(0, '@lsp.type.operator', { link = "Operator" })
vim.api.nvim_set_hl(0, '@lsp.type.parameter', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, '@lsp.type.property', { fg = "#953800" })
vim.api.nvim_set_hl(0, '@lsp.type.regexp', { fg = "#0a3069" })
vim.api.nvim_set_hl(0, '@lsp.type.string', { link = "String" })
vim.api.nvim_set_hl(0, '@lsp.type.struct', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, '@lsp.type.type', { link = "Type" })
vim.api.nvim_set_hl(0, '@lsp.type.typeParameter', { fg = "#953800" })
vim.api.nvim_set_hl(0, '@lsp.type.variable', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, '@macro', { link = "Macro" })
vim.api.nvim_set_hl(0, '@markup.heading', { link = "Title" })
vim.api.nvim_set_hl(0, '@markup.heading.1', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, '@markup.heading.2', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, '@markup.heading.3', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, '@markup.heading.4', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, '@markup.heading.5', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, '@markup.heading.6', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, '@markup.italic', {
  fg = "#1f2328",
  italic = true
})
vim.api.nvim_set_hl(0, '@markup.link', { fg = "#0969da" })
vim.api.nvim_set_hl(0, '@markup.link.label', { fg = "#0969da" })
vim.api.nvim_set_hl(0, '@markup.link.url', {
  fg = "#0969da",
  underline = true
})
vim.api.nvim_set_hl(0, '@markup.list', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, '@markup.list.checked', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, '@markup.list.unchecked', { fg = "#59636e" })
vim.api.nvim_set_hl(0, '@markup.math', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@markup.quote', {
  fg = "#59636e",
  italic = true
})
vim.api.nvim_set_hl(0, '@markup.raw', { fg = "#0a3069" })
vim.api.nvim_set_hl(0, '@markup.raw.block', { fg = "#0a3069" })
vim.api.nvim_set_hl(0, '@markup.strikethrough', {
  fg = "#1f2328",
  strikethrough = true
})
vim.api.nvim_set_hl(0, '@markup.strong', {
  fg = "#1f2328",
  bold = true
})
vim.api.nvim_set_hl(0, '@markup.underline', { underline = true })
vim.api.nvim_set_hl(0, '@method', { link = "Function" })
vim.api.nvim_set_hl(0, '@method.call', { link = "Function" })
vim.api.nvim_set_hl(0, '@module', { fg = "#953800" })
vim.api.nvim_set_hl(0, '@module.builtin', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@namespace', { fg = "#953800" })
vim.api.nvim_set_hl(0, '@number', { link = "Number" })
vim.api.nvim_set_hl(0, '@number.float', { link = "Float" })
vim.api.nvim_set_hl(0, '@operator', { link = "Operator" })
vim.api.nvim_set_hl(0, '@parameter', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, '@preproc', { link = "PreProc" })
vim.api.nvim_set_hl(0, '@property', { fg = "#953800" })
vim.api.nvim_set_hl(0, '@punctuation', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, '@punctuation.special', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, '@repeat', { link = "Repeat" })
vim.api.nvim_set_hl(0, '@storageclass', { link = "StorageClass" })
vim.api.nvim_set_hl(0, '@string', { link = "String" })
vim.api.nvim_set_hl(0, '@string.documentation', { fg = "#59636e" })
vim.api.nvim_set_hl(0, '@string.escape', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@string.regex', { fg = "#0a3069" })
vim.api.nvim_set_hl(0, '@string.regexp', { fg = "#0a3069" })
vim.api.nvim_set_hl(0, '@string.special', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@string.special.path', { fg = "#0a3069" })
vim.api.nvim_set_hl(0, '@string.special.symbol', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@string.special.url', {
  fg = "#0969da",
  underline = true
})
vim.api.nvim_set_hl(0, '@structure', { link = "Structure" })
vim.api.nvim_set_hl(0, '@tag', { link = "Tag" })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = "#953800" })
vim.api.nvim_set_hl(0, '@tag.builtin', { link = "Tag" })
vim.api.nvim_set_hl(0, '@tag.delimiter', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, '@text', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, '@text.literal', { link = "String" })
vim.api.nvim_set_hl(0, '@text.reference', { fg = "#0969da" })
vim.api.nvim_set_hl(0, '@text.title', { link = "Title" })
vim.api.nvim_set_hl(0, '@text.todo', { link = "Todo" })
vim.api.nvim_set_hl(0, '@text.underline', { underline = true })
vim.api.nvim_set_hl(0, '@text.uri', {
  fg = "#0969da",
  underline = true
})
vim.api.nvim_set_hl(0, '@type', { link = "Type" })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@type.definition', { link = "Type" })
vim.api.nvim_set_hl(0, '@type.qualifier', { link = "Keyword" })
vim.api.nvim_set_hl(0, '@variable', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@variable.member', { fg = "#953800" })
vim.api.nvim_set_hl(0, '@variable.parameter', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, '@variable.parameter.builtin', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, '@warning', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'Added', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'Boolean', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, 'Changed', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'Character', { fg = "#0a3069" })
vim.api.nvim_set_hl(0, 'CmpItemAbbr', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', {
  fg = "#6e7781",
  strikethrough = true
})
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'CmpItemKind', { fg = "#59636e" })
vim.api.nvim_set_hl(0, 'CmpItemKindClass', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, 'CmpItemKindColor', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, 'CmpItemKindConstructor', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, 'CmpItemKindDefault', { fg = "#59636e" })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, 'CmpItemKindEvent', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, 'CmpItemKindField', { fg = "#953800" })
vim.api.nvim_set_hl(0, 'CmpItemKindFile', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'CmpItemKindFolder', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, 'CmpItemKindModule', { fg = "#953800" })
vim.api.nvim_set_hl(0, 'CmpItemKindOperator', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'CmpItemKindProperty', { fg = "#953800" })
vim.api.nvim_set_hl(0, 'CmpItemKindReference', { fg = "#953800" })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', { fg = "#8250df" })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, 'CmpItemKindText', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter', { fg = "#953800" })
vim.api.nvim_set_hl(0, 'CmpItemKindUnit', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, 'CmpItemKindValue', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, 'CmpItemKindVariable', { fg = "#953800" })
vim.api.nvim_set_hl(0, 'CmpItemMenu', { fg = "#59636e" })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = "#f6f8fa" })
vim.api.nvim_set_hl(0, 'Comment', {
  fg = "#59636e",
  italic = true
})
vim.api.nvim_set_hl(0, 'ComplMatchIns', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, 'Conceal', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'Conditional', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'Constant', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, 'CurSearch', { link = "IncSearch" })
vim.api.nvim_set_hl(0, 'Cursor', {
  fg = "#ffffff",
  bg = "#1f2328"
})
vim.api.nvim_set_hl(0, 'CursorColumn', { link = "CursorLine" })
vim.api.nvim_set_hl(0, 'CursorIM', { link = "Cursor" })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = "#f6f8fa" })
vim.api.nvim_set_hl(0, 'CursorLineFold', {
  fg = "#6e7781",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'CursorLineNr', {
  fg = "#1f2328",
  bold = true
})
vim.api.nvim_set_hl(0, 'CursorLineSign', { bg = "#f6f8fa" })
vim.api.nvim_set_hl(0, 'Debug', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'Define', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'Delimiter', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'DiagnosticDeprecated', {
  sp = "#d1242f",
  strikethrough = true
})
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingError', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingHint', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingInfo', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingOk', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'DiagnosticFloatingWarn', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'DiagnosticOk', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'DiagnosticSignError', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'DiagnosticSignHint', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'DiagnosticSignInfo', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'DiagnosticSignOk', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'DiagnosticSignWarn', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', {
  sp = "#d1242f",
  undercurl = true
})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', {
  sp = "#1a7f37",
  undercurl = true
})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', {
  sp = "#0969da",
  undercurl = true
})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineOk', {
  sp = "#1a7f37",
  undercurl = true
})
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', {
  sp = "#9a6700",
  undercurl = true
})
vim.api.nvim_set_hl(0, 'DiagnosticUnnecessary', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', {
  fg = "#d1242f",
  bg = "#ffebe9"
})
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', {
  fg = "#1a7f37",
  bg = "#dafbe1"
})
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', {
  bg = "#54aeff",
  fg = "#0969da",
  blend = 60
})
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextOk', {
  fg = "#1a7f37",
  bg = "#dafbe1"
})
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', {
  fg = "#9a6700",
  bg = "#fff8c5"
})
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'DiffAdd', { bg = "#dafbe1" })
vim.api.nvim_set_hl(0, 'DiffChange', { bg = "#fff8c5" })
vim.api.nvim_set_hl(0, 'DiffDelete', { bg = "#ffebe9" })
vim.api.nvim_set_hl(0, 'DiffText', { bg = "#9a6700" })
vim.api.nvim_set_hl(0, 'Directory', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'Error', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'Exception', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'Float', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, 'FloatBorder', {
  fg = "#d1d9e0",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'FloatFooter', {
  fg = "#59636e",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'FloatTitle', {
  bg = "#ffffff",
  fg = "#1f2328",
  bold = true
})
vim.api.nvim_set_hl(0, 'FoldColumn', {
  fg = "#6e7781",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'Folded', {
  fg = "#59636e",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'Function', { fg = "#6639ba" })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'GitSignsAddLn', { bg = "#dafbe1" })
vim.api.nvim_set_hl(0, 'GitSignsAddNr', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'GitSignsChangeLn', { bg = "#fff8c5" })
vim.api.nvim_set_hl(0, 'GitSignsChangeNr', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'GitSignsDeleteLn', { bg = "#ffebe9" })
vim.api.nvim_set_hl(0, 'GitSignsDeleteNr', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'IblIndent', { fg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'IblScope', { fg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'IblWhitespace', { fg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'Identifier', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'Ignore', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'IncSearch', {
  fg = "#ffffff",
  bg = "#0969da"
})
vim.api.nvim_set_hl(0, 'Include', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'IndentBlanklineChar', { fg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextChar', { fg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextStart', {
  sp = "#d1d9e0",
  underline = true
})
vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceChar', { fg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceCharBlankline', { fg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'Keyword', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'Label', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'LazyButton', {
  fg = "#1f2328",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'LazyButtonActive', {
  fg = "#ffffff",
  bg = "#0969da"
})
vim.api.nvim_set_hl(0, 'LazyCommit', { fg = "#59636e" })
vim.api.nvim_set_hl(0, 'LazyCommitType', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'LazyH1', {
  bg = "#0969da",
  fg = "#ffffff",
  bold = true
})
vim.api.nvim_set_hl(0, 'LazyH2', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, 'LazyNormal', { link = "NormalFloat" })
vim.api.nvim_set_hl(0, 'LazyReasonCmd', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'LazyReasonEvent', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'LazyReasonFt', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'LazyReasonKeys', { fg = "#8250df" })
vim.api.nvim_set_hl(0, 'LazyReasonPlugin', { fg = "#8250df" })
vim.api.nvim_set_hl(0, 'LazyReasonStart', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'LazySpecial', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'LineNr', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'LineNrAbove', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'LineNrBelow', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'LspCodeLens', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'LspCodeLensSeparator', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'LspInlayHint', {
  fg = "#6e7781",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'LspReferenceRead', {
  bg = "#54aeff",
  blend = 60
})
vim.api.nvim_set_hl(0, 'LspReferenceTarget', {
  bg = "#54aeff",
  blend = 60
})
vim.api.nvim_set_hl(0, 'LspReferenceText', {
  bg = "#54aeff",
  blend = 60
})
vim.api.nvim_set_hl(0, 'LspReferenceWrite', {
  bg = "#54aeff",
  blend = 60
})
vim.api.nvim_set_hl(0, 'LspSignatureActiveParameter', {
  bold = true,
  fg = "#0969da",
  underline = true
})
vim.api.nvim_set_hl(0, 'Macro', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, 'MatchParen', {
  bg = "#54aeff",
  blend = 60,
  bold = true
})
vim.api.nvim_set_hl(0, 'ModeMsg', {
  fg = "#1f2328",
  bold = true
})
vim.api.nvim_set_hl(0, 'MoreMsg', {
  fg = "#1a7f37",
  bold = true
})
vim.api.nvim_set_hl(0, 'MsgArea', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'MsgSeparator', { fg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'NeoTreeDirectoryIcon', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'NeoTreeDirectoryName', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'NeoTreeEndOfBuffer', { fg = "#f6f8fa" })
vim.api.nvim_set_hl(0, 'NeoTreeFileIcon', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'NeoTreeFileName', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'NeoTreeGitAdded', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'NeoTreeGitConflict', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'NeoTreeGitDeleted', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'NeoTreeGitIgnored', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'NeoTreeGitModified', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'NeoTreeGitStaged', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'NeoTreeGitUnstaged', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'NeoTreeGitUntracked', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'NeoTreeIndentMarker', { fg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'NeoTreeNormal', {
  fg = "#1f2328",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'NeoTreeNormalNC', {
  fg = "#1f2328",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'NeoTreeRootName', {
  fg = "#59636e",
  bold = true
})
vim.api.nvim_set_hl(0, 'NonText', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'Normal', {
  fg = "#1f2328",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'NormalFloat', {
  fg = "#1f2328",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'NormalNC', {
  fg = "#1f2328",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'Number', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, 'NvimTreeEmptyFolderName', { fg = "#59636e" })
vim.api.nvim_set_hl(0, 'NvimTreeEndOfBuffer', { fg = "#f6f8fa" })
vim.api.nvim_set_hl(0, 'NvimTreeFolderIcon', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'NvimTreeFolderName', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'NvimTreeGitDeleted', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'NvimTreeGitDirty', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'NvimTreeGitNew', { fg = "#1a7f37" })
vim.api.nvim_set_hl(0, 'NvimTreeImageFile', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'NvimTreeIndentMarker', { fg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'NvimTreeNormal', {
  fg = "#1f2328",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'NvimTreeOpenedFolderName', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'NvimTreeRootFolder', {
  fg = "#59636e",
  bold = true
})
vim.api.nvim_set_hl(0, 'NvimTreeSpecialFile', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'NvimTreeSymlink', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'Operator', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'Pmenu', {
  fg = "#1f2328",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'PmenuExtra', {
  fg = "#6e7781",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'PmenuExtraSel', {
  bg = "#54aeff",
  fg = "#6e7781",
  blend = 60
})
vim.api.nvim_set_hl(0, 'PmenuKind', {
  fg = "#59636e",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'PmenuKindSel', {
  bg = "#54aeff",
  fg = "#59636e",
  blend = 60
})
vim.api.nvim_set_hl(0, 'PmenuMatch', {
  bg = "#ffffff",
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, 'PmenuMatchSel', {
  bg = "#54aeff",
  blend = 60,
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = "#f6f8fa" })
vim.api.nvim_set_hl(0, 'PmenuSel', {
  bg = "#54aeff",
  fg = "#1f2328",
  blend = 60
})
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'PreCondit', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'PreProc', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'Question', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'QuickFixLine', {
  bg = "#54aeff",
  blend = 60
})
vim.api.nvim_set_hl(0, 'Removed', { fg = "#d1242f" })
vim.api.nvim_set_hl(0, 'Repeat', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'Search', {
  fg = "#1f2328",
  bg = "#9a6700"
})
vim.api.nvim_set_hl(0, 'SignColumn', {
  fg = "#6e7781",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'SnippetTabstop', {
  bg = "#54aeff",
  blend = 60
})
vim.api.nvim_set_hl(0, 'Special', { fg = "#0550ae" })
vim.api.nvim_set_hl(0, 'SpecialChar', { fg = "#0a3069" })
vim.api.nvim_set_hl(0, 'SpecialComment', {
  italic = true,
  fg = "#59636e",
  bold = true
})
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'SpellBad', {
  sp = "#d1242f",
  undercurl = true
})
vim.api.nvim_set_hl(0, 'SpellCap', {
  sp = "#9a6700",
  undercurl = true
})
vim.api.nvim_set_hl(0, 'SpellLocal', {
  sp = "#0969da",
  undercurl = true
})
vim.api.nvim_set_hl(0, 'SpellRare', {
  sp = "#8250df",
  undercurl = true
})
vim.api.nvim_set_hl(0, 'Statement', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'StatusLine', {
  fg = "#59636e",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'StatusLineNC', {
  fg = "#6e7781",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'StatusLineTerm', {
  fg = "#59636e",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'StatusLineTermNC', {
  fg = "#6e7781",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'StorageClass', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'String', { fg = "#0a3069" })
vim.api.nvim_set_hl(0, 'Structure', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'Substitute', {
  fg = "#ffffff",
  bg = "#cf222e"
})
vim.api.nvim_set_hl(0, 'TabLine', {
  fg = "#59636e",
  bg = "#f6f8fa"
})
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = "#f6f8fa" })
vim.api.nvim_set_hl(0, 'TabLineSel', {
  fg = "#1f2328",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'Tag', { fg = "#116329" })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { link = "FloatBorder" })
vim.api.nvim_set_hl(0, 'TelescopeMatching', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, 'TelescopeMultiSelection', {
  bg = "#54aeff",
  fg = "#1f2328",
  blend = 60
})
vim.api.nvim_set_hl(0, 'TelescopeNormal', { link = "NormalFloat" })
vim.api.nvim_set_hl(0, 'TelescopePreviewBorder', {
  fg = "#d1d9e0",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopePreviewNormal', {
  fg = "#1f2328",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopePreviewTitle', {
  fg = "#1f2328",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopePromptBorder', {
  fg = "#d1d9e0",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopePromptNormal', {
  fg = "#1f2328",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopePromptPrefix', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'TelescopePromptTitle', {
  bg = "#ffffff",
  fg = "#1f2328",
  bold = true
})
vim.api.nvim_set_hl(0, 'TelescopeResultsBorder', {
  fg = "#d1d9e0",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopeResultsNormal', {
  fg = "#1f2328",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopeResultsTitle', {
  fg = "#1f2328",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'TelescopeSelection', { link = "PmenuSel" })
vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'TelescopeTitle', { link = "FloatTitle" })
vim.api.nvim_set_hl(0, 'TermCursor', { link = "Cursor" })
vim.api.nvim_set_hl(0, 'TermCursorNC', {
  fg = "#ffffff",
  bg = "#59636e"
})
vim.api.nvim_set_hl(0, 'Title', {
  fg = "#0969da",
  bold = true
})
vim.api.nvim_set_hl(0, 'Todo', {
  fg = "#9a6700",
  bold = true
})
vim.api.nvim_set_hl(0, 'Type', { fg = "#953800" })
vim.api.nvim_set_hl(0, 'Typedef', { fg = "#cf222e" })
vim.api.nvim_set_hl(0, 'Underlined', {
  fg = "#0969da",
  underline = true
})
vim.api.nvim_set_hl(0, 'VertSplit', { link = "WinSeparator" })
vim.api.nvim_set_hl(0, 'Visual', {
  bg = "#54aeff",
  blend = 60
})
vim.api.nvim_set_hl(0, 'VisualNOS', { link = "Visual" })
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = "#9a6700" })
vim.api.nvim_set_hl(0, 'WhichKey', { fg = "#0969da" })
vim.api.nvim_set_hl(0, 'WhichKeyBorder', { link = "FloatBorder" })
vim.api.nvim_set_hl(0, 'WhichKeyDesc', { fg = "#1f2328" })
vim.api.nvim_set_hl(0, 'WhichKeyFloat', { link = "NormalFloat" })
vim.api.nvim_set_hl(0, 'WhichKeyGroup', { fg = "#8250df" })
vim.api.nvim_set_hl(0, 'WhichKeySeparator', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'WhichKeyValue', { fg = "#59636e" })
vim.api.nvim_set_hl(0, 'Whitespace', { fg = "#6e7781" })
vim.api.nvim_set_hl(0, 'WildMenu', { link = "PmenuSel" })
vim.api.nvim_set_hl(0, 'WinBar', {
  bg = "#ffffff",
  fg = "#1f2328",
  bold = true
})
vim.api.nvim_set_hl(0, 'WinBarNC', {
  fg = "#59636e",
  bg = "#ffffff"
})
vim.api.nvim_set_hl(0, 'WinSeparator', { fg = "#d1d9e0" })
vim.api.nvim_set_hl(0, 'lCursor', { link = "Cursor" })

-- Terminal colors
vim.g.terminal_color_0 = '#24292f'
vim.g.terminal_color_1 = '#cf222e'
vim.g.terminal_color_2 = '#116329'
vim.g.terminal_color_3 = '#4d2d00'
vim.g.terminal_color_4 = '#0969da'
vim.g.terminal_color_5 = '#8250df'
vim.g.terminal_color_6 = '#1b7c83'
vim.g.terminal_color_7 = '#6e7781'
vim.g.terminal_color_8 = '#57606a'
vim.g.terminal_color_9 = '#a40e26'
vim.g.terminal_color_10 = '#1a7f37'
vim.g.terminal_color_11 = '#633c01'
vim.g.terminal_color_12 = '#218bff'
vim.g.terminal_color_13 = '#a475f9'
vim.g.terminal_color_14 = '#3192aa'
vim.g.terminal_color_15 = '#8c959f'

-- vi:nowrap
